USE OptioWorkTime;

INSERT INTO Shifts VALUES (1, 'I', 1);
INSERT INTO Shifts VALUES (2, 'II', 1);
INSERT INTO Shifts VALUES (3, 'III', 1);
INSERT INTO Shifts VALUES (4, 'IV', 1);
INSERT INTO Shifts VALUES (5, 'V', 1);
INSERT INTO Shifts VALUES (6, 'VI', 1);
INSERT INTO Shifts VALUES (7, 'VII', 1);
INSERT INTO Shifts VALUES (8, 'VIII', 1);
INSERT INTO Shifts VALUES (9, 'IX', 1);
INSERT INTO Shifts VALUES (10, 'X', 1);
INSERT INTO Shifts VALUES (11, 'XI', 1);
INSERT INTO Shifts VALUES (12, 'XII', 1);
INSERT INTO Shifts VALUES (13, 'XIII', 1);
INSERT INTO Shifts VALUES (14, 'XIV', 1);
INSERT INTO Shifts VALUES (15, 'XV', 0);
INSERT INTO Shifts VALUES (16, 'XVI', 0);
INSERT INTO Shifts VALUES (17, 'XVII', 0);
INSERT INTO Shifts VALUES (18, 'XVIII', 0);
INSERT INTO Shifts VALUES (19, 'XIX', 0);
INSERT INTO Shifts VALUES (20, 'XX', 0);
INSERT INTO Shifts VALUES (40, 'N', 1);
INSERT INTO Shifts VALUES (41, 'NS', 1);
INSERT INTO Shifts VALUES (42, 'D5', 1);

INSERT INTO ShiftDurations VALUES (1, );